# Generated by Django 3.2 on 2022-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Электронная почта')),
                ('text', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('status', models.CharField(blank=True, choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='Новая', max_length=13, null=True, verbose_name='Статус')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
